layout_spectrum: 0.1729404875545735
typography_spectrum: 0.4972862449111325
color:
  brandColors:
    - '#1C1D21'
    - '#31353D'
    - '#445878'
    - '#92CDCF'
    - '#EEEFF7'
  brandStrength: 0.1694713464835751
  lightness: 0.25296373084178286
  saturation: 0.8260687200465967
  rhythmicContrast: 0.691521863386791
coverPrefs:
  filter: false
name: The Grid Android
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/5ec3a55f-dd2d-4247-97ef-92794a699082.png
opengraph:
  type: ''
  appId: ''
purpose:
  - type: external
    label: Install the app
    url: 'https://play.google.com/store/apps/details?id=io.thegrid.app'
  - type: external
    label: Become a beta tester
    url: 'https://play.google.com/apps/testing/io.thegrid.app'
title: The Grid Android App
description: Build websites everywhere
author: {}
content_rating:
  adult: false
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/caea2d6e-e6c0-4a05-a16a-e8decf65a71d.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/caea2d6e-e6c0-4a05-a16a-e8decf65a71d.png
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
github: true
