typography_spectrum: 0.9771365351043642
content_rating:
  adult: false
color:
  brandColors:
    - '#B9121B'
    - '#4C1B1B'
    - '#F6E497'
    - '#FCFAE1'
    - '#BD8D46'
  brandStrength: 0.6958279928658158
  lightness: 0.832026107236743
  saturation: 0.439751481404528
  rhythmicContrast: 0.7959500951692462
github: true
opengraph:
  type: ''
  appId: ''
layout_spectrum: 0.34409413463436067
author: {}
name: Android
navigation:
  - name: Youtube
    url: 'http://youtube.com'
    type: external
  - name: This is a tent!!!
    id: 445410e4-8c27-4757-9e3c-24be0fb4c063
    type: content
title: cool!
content: []
description: The best mobile OS™
purpose:
  - type: contact
    label: oh
    url: 'mailto:x@hannesstruss.de'
  - type: contact
    label: Call 234
    url: 'tel:234'
