name: Android
layout_spectrum: 0.34409413463436067
typography_spectrum: 0.9771365351043642
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#B9121B'
    - '#4C1B1B'
    - '#F6E497'
    - '#FCFAE1'
    - '#BD8D46'
  brandStrength: 0.6958279928658158
  lightness: 0.832026107236743
  saturation: 0.439751481404528
  rhythmicContrast: 0.7959500951692462
purpose:
  - type: contact
    url: 'tel:+20123123'
    label: Call +20123123
  - type: external
    url: '+234234'
    label: '+234234'
title: cool!
description: ''
author:
  name: ''
  url: ''
  email: ''
content_rating:
  adult: false
navigation:
  - name: asdxxxxx
    id: ca74c8cc-cbba-4b1b-b21e-229bac52728d
    type: content
  - name: dfgdfg
    url: dfgdfg
    type: external
github: true
