typography_spectrum: 0.9771365351043642
content_rating:
  adult: false
color:
  brandColors:
    - '#B9121B'
    - '#4C1B1B'
    - '#F6E497'
    - '#FCFAE1'
    - '#BD8D46'
  brandStrength: 0.6958279928658158
  lightness: 0.832026107236743
  rhythmicContrast: 0.7959500951692462
  saturation: 0.439751481404528
opengraph:
  appId: ''
  type: ''
layout_spectrum: 0.34409413463436067
author:
  email: ''
  name: ''
  url: ''
name: Android
navigation:
  - name: dfgdfg
    url: dfgdfg
    type: external
  - name: asd
    id: ca74c8cc-cbba-4b1b-b21e-229bac52728d
    type: content
title: cool!
