name: Android
layout_spectrum: 0.34409413463436067
typography_spectrum: 0.9771365351043642
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#B9121B'
    - '#4C1B1B'
    - '#F6E497'
    - '#FCFAE1'
    - '#BD8D46'
  brandStrength: 0.6958279928658158
  lightness: 0.832026107236743
  saturation: 0.439751481404528
  rhythmicContrast: 0.7959500951692462
purpose: []
title: cool!
description: The best mobile OS™
author: {}
content_rating:
  adult: false
content: []
github: true
