typography_spectrum: 0.9771365351043642
content_rating:
  adult: false
color:
  brandColors:
    - '#B9121B'
    - '#4C1B1B'
    - '#F6E497'
    - '#FCFAE1'
    - '#BD8D46'
  brandStrength: 0.6958279928658158
  lightness: 0.832026107236743
  saturation: 0.439751481404528
  rhythmicContrast: 0.7959500951692462
github: true
opengraph:
  type: ''
  appId: ''
layout_spectrum: 0.34409413463436067
author:
  name: ''
  url: ''
  email: ''
name: Android
navigation:
  - name: This is a tent!!!
    id: 445410e4-8c27-4757-9e3c-24be0fb4c063
    type: content
title: cool!
content: []
description: asd
purpose:
  - type: internal
    label: asd
    item: bc003512-5cc7-4584-83bd-e1b3b46ed360
